### PR TITLE
update deps

### PR DESCRIPTION
**Pull request by gabeweaver**
# Why
So we can stay current and to prepare the booster kit for migration to
React Hot Loader 3, Webpack 2.1, and React-router 4

# What
* Updates deps
* Removes history and react-router-redux dependencies
* Refactors client.js, reducer, and createStore to handle route
locations without those two deps.
* Adds support for express server. This is meant to provide options and
things for folks to explore both koa and/or express (and potentially
tee up adding server side rendering down the road)
* Cleans up configs a bit

### CODE REVIEW

**Comment by gabeweaver** [comment]
@samcdavid to provide options/playgrounds for using the two different server techs. I like koa and its potential, express is stable. Eventually i want to create smaller packages.json files that inherit from one another so we can have all the koa deps in a packages.json file in the `koa` directory. 

Will it just work out of the gate if we split it up that way or should we structure packages a bit more intentionally like http://staltz.com/setting-up-a-javascript-monorepo.html? 

The intent behind this isn't for the servers specifically but I'd like to figure out a good pattern for managing different packages like the component library and stuff... thoughts?

**Comment by samcdavid** [comment]
I would prefer that we just pick one and support that. We'll have all kinds of problems if we try to support many different versions. Think, MVP :trollface: :smile:

**Comment by gabeweaver** [comment]
@samcdavid removed Koa as a server dep. As a side note, when should we start using official github releases?

**Comment by squaresurf** [comment]
Please delete your branches once they've been merged into master.

**Pull request merged**
